coverage:
  # Commit status https://docs.codecov.io/docs/commit-status are used
  # to block PR based on coverage threshold.
  status:
    project:
      default:
        # Temporarily lowering below 80% to unblock PRs
        target: 75
        threshold: 5%
    patch:
      # Disable the coverage threshold of the patch, so that PRs are
      # only failing because of overall project coverage threshold.
      # See https://docs.codecov.io/docs/commit-status#disabling-a-status.
      default: false
comment:
  # Update existing comment or create new if deleted.
  behavior: default
ignore:
  - "**/zz_generated*.go" # Ignore generated files.
  - "**/*.pb.go" # Ignore proto-generated files.
  - "hack"
  - "pkg/client"
  - "test"
  - "third_party"
