defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  knative.dev/client/cmd/kn: docker.io/library/alpine:latest
builds:
  - id: knative.dev/client/cmd/kn
    main: ./cmd/kn
    ldflags:
      - -X knative.dev/client/pkg/commands/version.Version={{.Env.KN_BUILD_VERSION}}
      - -X knative.dev/client/pkg/commands/version.GitRevision={{.Env.KN_BUILD_GITREV}}
      - -X 'knative.dev/client/pkg/commands/version.BuildDate={{.Env.KN_BUILD_DATE}}'
