# Copyright 2022 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is automagically synced here from github.com/knative-extensions/knobots

name: Test

on:
  push:
    branches: [ 'main', 'release-*' ]

  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  test:
    uses: cardil/knative-actions/.github/workflows/reusable-go-test.yaml@feature/unit-test-each-go-module
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
